[package]
name = "route_based_mdp_ddarp"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
priority-queue = "2.1.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
toml = "0.8.14"
